import { Inter } from "next/font/google";
import "./globals.css";
import FirebaseProviderWrapper from "./components/FirebaseProviderWrapper"; // Import the client component

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FirebaseProviderWrapper> 
          {children}
        </FirebaseProviderWrapper>
      </body>
    </html>
  );
}
